#!/usr/bin/env bash

# Copyright 2026 The kcp Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# A throwaway Dex, shared by every component's e2e and by local development.
#
# All three virtual workspaces authenticate callers the same way kcp does —
# by pointing at the same AuthenticationConfiguration — so an identity
# provider belongs here rather than in any one component. This script
# stands one up and writes the file both sides consume.
#
#   hack/dex/dex.sh up [workdir]     start Dex, write config + CA + auth config
#   hack/dex/dex.sh down             stop it
#   hack/dex/dex.sh token USER       print an ID token for a test user
#   hack/dex/dex.sh env [workdir]    print the variables the e2e harnesses read
#
# Environment:
#   DEX_PORT       host port Dex serves on (default 5556)
#   DEX_IMAGE      container image (default ghcr.io/dexidp/dex:v2.44.0)
#   DEX_NAME       container name (default kcp-contrib-dex)
#   DEX_PASSWORD   the one password every test user has (default "password")

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

DEX_PORT="${DEX_PORT:-5556}"
DEX_IMAGE="${DEX_IMAGE:-ghcr.io/dexidp/dex:v2.44.0}"
DEX_NAME="${DEX_NAME:-kcp-contrib-dex}"
DEX_PASSWORD="${DEX_PASSWORD:-password}"
DEX_CLIENT_ID="${DEX_CLIENT_ID:-kcp}"
DEX_ISSUER="https://localhost:${DEX_PORT}/dex"

# The test identities. The email is the whole identity: the
# AuthenticationConfiguration maps the local part to a username and the
# first label of the domain to a group, so these produce exactly the same
# users and groups the certificate-based harness mints — alice in team-a,
# bob in team-b, mallory in strangers — and a test can switch between the
# two credentials without changing a single Membership.
DEX_USERS=(
  "alice:alice@team-a.example.com"
  "bob:bob@team-b.example.com"
  "mallory:mallory@strangers.example.com"
)

log() { printf '\033[1;32m==>\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31mERR\033[0m %s\n' "$*" >&2; exit 1; }

# email_for maps a short test name to the identity Dex knows.
email_for() {
  local want="$1" entry
  for entry in "${DEX_USERS[@]}"; do
    if [[ "${entry%%:*}" == "${want}" ]]; then
      echo "${entry#*:}"
      return 0
    fi
  done
  die "unknown test user ${want}; known: $(printf '%s ' "${DEX_USERS[@]%%:*}")"
}

bcrypt_hash() { # password -> bcrypt hash, using the repo's own module
  local pw="$1" gen
  gen="$(mktemp -d)"
  cat > "${gen}/main.go" <<'GO'
package main

import (
	"fmt"
	"os"

	"golang.org/x/crypto/bcrypt"
)

func main() {
	h, err := bcrypt.GenerateFromPassword([]byte(os.Args[1]), 10)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(h))
}
GO
  (cd "${REPO_ROOT}" && go run "${gen}/main.go" "${pw}")
  rm -rf "${gen}"
}

cmd_up() {
  local workdir="${1:-${REPO_ROOT}/.dex}"
  mkdir -p "${workdir}"

  command -v docker >/dev/null 2>&1 || die "docker is required to run Dex"

  # Dex must serve HTTPS: Kubernetes refuses a plain-http OIDC issuer, and
  # the certificate goes into the AuthenticationConfiguration so both kcp
  # and the virtual workspaces trust exactly this one.
  if ! openssl x509 -in "${workdir}/tls.crt" -checkend 3600 >/dev/null 2>&1; then
    log "generating Dex serving certificate"
    openssl req -x509 -newkey rsa:2048 -nodes -days 30 \
      -keyout "${workdir}/tls.key" -out "${workdir}/tls.crt" \
      -subj "/CN=localhost" \
      -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" >/dev/null 2>&1
  fi

  log "writing Dex configuration"
  local hash
  hash="$(bcrypt_hash "${DEX_PASSWORD}")"

  {
    cat <<EOF
# Generated by hack/dex/dex.sh — do not edit.
issuer: ${DEX_ISSUER}
storage:
  type: memory
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls.crt
  tlsKey: /etc/dex/tls.key
oauth2:
  # The tests have no browser, so they use the resource-owner password
  # grant. That needs a connector nominated for it and a public client.
  passwordConnector: local
  skipApprovalScreen: true
staticClients:
  - id: ${DEX_CLIENT_ID}
    public: true
    name: kcp
    redirectURIs: ['http://localhost:8000/callback']
enablePasswordDB: true
staticPasswords:
EOF
    local i=0 entry email
    for entry in "${DEX_USERS[@]}"; do
      i=$((i + 1))
      email="${entry#*:}"
      cat <<EOF
  - email: ${email}
    hash: "${hash}"
    username: ${entry%%:*}
    userID: "${i}"
EOF
    done
  } > "${workdir}/dex.yaml"

  # Dex's password database carries no groups — that is a property of the
  # connector, not a misconfiguration — so groups are derived here from the
  # email domain. Deriving identity attributes with CEL is exactly what
  # structured authentication is for, and it keeps the test users' groups
  # identical to the certificate harness's.
  {
    cat <<EOF
# Generated by hack/dex/dex.sh — do not edit.
#
# The same file is given to kcp (--authentication-config) and to every
# virtual workspace, so a username cannot drift between the two. A caller
# authenticated by kcp and the same caller authenticated by a virtual
# workspace are the same string, which is what Membership subjects and RBAC
# compare against.
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: ${DEX_ISSUER}
      audiences: [${DEX_CLIENT_ID}]
      certificateAuthority: |
EOF
    sed 's/^/        /' "${workdir}/tls.crt"
    cat <<'EOF'
    claimMappings:
      # alice@team-a.example.com -> alice
      username:
        expression: "claims.email.split('@')[0]"
      # ...and -> [team-a]
      groups:
        expression: "[claims.email.split('@')[1].split('.')[0]]"
    claimValidationRules:
      # Kubernetes refuses to derive a username from an unverified email,
      # and says so at startup rather than at request time.
      - expression: "claims.email_verified == true"
        message: "the identity provider must assert a verified email"
EOF
  } > "${workdir}/authentication-config.yaml"

  docker rm -f "${DEX_NAME}" >/dev/null 2>&1 || true
  log "starting Dex on :${DEX_PORT} (${DEX_IMAGE})"
  docker run -d --name "${DEX_NAME}" \
    -p "${DEX_PORT}:5556" \
    -v "${workdir}/dex.yaml:/etc/dex/config.yaml:ro" \
    -v "${workdir}/tls.crt:/etc/dex/tls.crt:ro" \
    -v "${workdir}/tls.key:/etc/dex/tls.key:ro" \
    "${DEX_IMAGE}" dex serve /etc/dex/config.yaml >/dev/null

  local ready=false i
  for i in $(seq 1 60); do
    if curl -ks "${DEX_ISSUER}/.well-known/openid-configuration" >/dev/null 2>&1; then
      ready=true
      break
    fi
    sleep 1
  done
  if [[ "${ready}" != "true" ]]; then
    docker logs "${DEX_NAME}" 2>&1 | tail -n 30 >&2
    die "Dex did not become ready"
  fi
  log "Dex ready at ${DEX_ISSUER}"
}

cmd_down() {
  docker rm -f "${DEX_NAME}" >/dev/null 2>&1 || true
}

cmd_token() {
  local user="${1:-}"
  [[ -n "${user}" ]] || die "usage: dex.sh token USER"
  local email
  email="$(email_for "${user}")"

  local response
  response="$(curl -ks -X POST "${DEX_ISSUER}/token" \
    -d grant_type=password \
    -d "client_id=${DEX_CLIENT_ID}" \
    -d "username=${email}" \
    -d "password=${DEX_PASSWORD}" \
    -d scope="openid email groups")"

  local token
  token="$(printf '%s' "${response}" | sed -n 's/.*"id_token":"\([^"]*\)".*/\1/p')"
  [[ -n "${token}" ]] || die "no id_token for ${email}: ${response}"
  printf '%s\n' "${token}"
}

cmd_env() {
  local workdir="${1:-${REPO_ROOT}/.dex}"
  cat <<EOF
export DEX_ISSUER=${DEX_ISSUER}
export DEX_CLIENT_ID=${DEX_CLIENT_ID}
export DEX_PASSWORD=${DEX_PASSWORD}
export DEX_CA_FILE=${workdir}/tls.crt
export DEX_AUTHENTICATION_CONFIG=${workdir}/authentication-config.yaml
EOF
}

case "${1:-}" in
  up)    shift; cmd_up "$@" ;;
  down)  shift; cmd_down "$@" ;;
  token) shift; cmd_token "$@" ;;
  env)   shift; cmd_env "$@" ;;
  *)     die "usage: dex.sh {up|down|token USER|env} [workdir]" ;;
esac
